### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by russback** [wbrowar/craft-guide#102]
Installed this for Craft 5 as I came across it in the plugin store. Looks useful but could see an issue whereby users with permission to view Guide could just see settings rather than the guide content, and then spotted that the docs refer to Craft 4 and there have been no releases for some time.

**Comment by wbrowar** [comment]
Hi, @russback. No the plugin is still in development, however, I've kept it under `beta` until I have fully tested everything out.

The Craft 4 mention is probably something I missed in the docs and I will look out for it and update the docs (thanks for the heads up).

Regarding the settings page, it's currently required that you save the settings to set a template directory. Then the Organizer should be available and once you've created at least one guide and have moved it to the CP Section you should be able to view them from the Guide CP section (instead of being re-directed to the settings pages). If there are no guides in the CP Section then you should get redirected to the Organizer.

If that doesn't work please let me know and I'll take a look. It sounds like it would be a good idea to show the reason why you got redirected in the UI.

**Comment by russback** [comment]
Hey @wbrowar 

A couple of things that might be helpful then.

When no asset volume was set, changes to the fields in the Variables tab aren't saved.

Once that's set and variables are set, the admin user sees this:

<img width="880" alt="Screenshot 2024-06-25 at 22 41 08" src="https://github.com/wbrowar/craft-guide/assets/2589006/cd8fa6de-4e6d-4737-89b9-cf0fcb742b5d">

And a user in a user group with that Overview permission sees this (still no content to view)

<img width="570" alt="Screenshot 2024-06-25 at 22 40 53" src="https://github.com/wbrowar/craft-guide/assets/2589006/baabd9c8-4157-4c44-b901-034fbcb1ca52">

**Comment by wmdhosting** [comment]
Anytime slideins will comeout :) waiting 2 years for that one..  :)

**Comment by wbrowar** [comment]
@russback, I was looking through the points you made above and I don't think there are currently any bugs, however, there's an opportunity for me to improve usability.

Regarding the settings in the Variables tab, those are independent from the settings in the General tab and there shouldn't be anything on the General page preventing Variables settings from saving. I'll continue to test this out, but could it be that you needed to hit **Save** before moving between General and Variables? In testing this myself I get an error in Chrome warning that hitting the General tab will not save changes on the Variables tab, however, I don't know that every browser will show this warning.

<img width="1174" alt="Screenshot 2024-08-11 at 5 30 22 PM" src="https://github.com/user-attachments/assets/5910bd14-71f6-4aad-bb27-affa82d2d698">

Please take a look and let me know if this is still an issue for you. If it is, I'll see if there is something going on with the plugin settings themselves.

---

> Once that's set and variables are set, the admin user sees this:

Screenshot 2024-06-25 at 22 41 08
And a user in a user group with that Overview permission sees this (still no content to view)

Screenshot 2024-06-25 at 22 40 53

For your second note I can see why it’s not clear. The guides need to be moved to the **Guide** section before they will appear in the Guide section for all users. In the next major version of Guide I plan on re-thinking the Organizer section to make it more intuitive.

---

Also to your point about the docs displaying Craft 4 info, my plan in the next major version in to remove that separate docs site and to move more back to the README file.. This way different versions of the docs will be version controlled along with Guide itself.

Thanks again for your input and I'll keep this issue open until some of the UI issues are addressed in the next major version of Guide.
