### ISSUE TITLE
[Bug] "Copy Guide Data" under utilities isn't working

### ISSUE THREAD

**Issue by KatieMFritz** [wbrowar/craft-guide#59]
## Steps to reproduce
1. Go to Utilities > Guide in my local site.
2. Select a Guide to copy.
3. Click "Copy Guide Data" button.

## What I expect to happen
JSON should be copied to my clipboard

## What happens instead
Nothing gets copied to my clipboard.
Console error:
> globals.779c1e1a.js:1 TypeError: Cannot read properties of undefined (reading 'writeText')
    at Proxy.copyText (guide-admin.0c2f1b3e.js:1:623577)
    at Proxy.copyExportData (guide-admin.0c2f1b3e.js:1:623957)
    at l.onClick.t.<computed>.t.<computed> (guide-admin.0c2f1b3e.js:1:625881)
    at Yr (globals.779c1e1a.js:1:56677)
    at es (globals.779c1e1a.js:1:56756)
    at HTMLButtonElement.n (globals.779c1e1a.js:1:64069)

**Comment by wbrowar** [comment]
Hi @KatieMFritz, I'm looking into this one and haven't been able to replicate it yet. Can you please tell me what browser you're using?

**Comment by iwe-hi** [comment]
Hi @wbrowar 
We have the same error in Chrome V99.0.48.44.74 on mac os arm64. In Firefox V98.0.1 we get a "navigator.clipboard is undefined" error.

**Comment by wbrowar** [comment]
Thanks, @KatieMFritz and @iwe-hi for the info! I was going to do some checks and swap out the copy button for a backup textfield when needed, but I sort of like the idea of letting you choose. So in this case the button shouldn't be there in a situation where the clipboard isn't accessible and you'd only see a text field, otherwise you’d see this:

<img width="1500" alt="Screen Shot 2022-03-27 at 7 33 14 PM" src="https://user-images.githubusercontent.com/2158662/160306023-724bb516-9883-429b-9314-db88d04b63ca.png">

I'm just wrapping up some other bugs and will have a fix out soon.

**Comment by wbrowar** [comment]
This has been released in [3.1.1](https://github.com/wbrowar/craft-guide/releases/tag/3.1.1)!
